name: Pull Request Workflow

on:
  workflow_call:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Install Dependencies
        run: make init
      - name: Vet Code 
        run: make vet
      - name: Check Go Formatting
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi
